name: "la-degradation"

routines:
  custom :
    "custom1":
        - ["dormir", 1]
        - ["agir", 36000]
        - ["dormir", 54000]
    "custom2":
          - ["dormir", 1]
          - ["rever", 36000]
          - ["dormir", 54000]
#    - "custom1": '{{"dormir","18000","36000"},{"agir","36001","54000"}, {"dormir","54001","62000"}}'
#    - "custom2": '{{"dormir","18000","36000"},{"rever","36001","54000"}, {"dormir","54001","62000"}}'
#    - "custom3": '{{"dormir","18000","36000"},{"travailler","36001","54000"}, {"dormir","54001","62000"}}'
#    - "custom4": '{{"dormir","18000","36000"},{"reflechir","36001","54000"}, {"dormir","54001","62000"}}'
#    - "custom5": '{{"dormir","18000","36000"},{"se-promener","36001","54000"}, {"dormir","54001","62000"}}'
#    - "custom6": '{{"dormir","18000","36000"},{"agir","36001","54000"}, {"dormir","54001","62000"}}'
#    - "custom7": '{{"dormir","18000","36000"},{"agir","36001","54000"}, {"dormir","54001","62000"}}'
#    - "custom8": '{{"dormir","18000","36000"},{"agir","36001","54000"}, {"dormir","54001","62000"}}'
#    - "custom9": '{{"dormir","18000","36000"},{"agir","36001","54000"}, {"dormir","54001","62000"}}'
#    - "custom10": '{{"dormir","18000","36000"},{"agir","36001","54000"}, {"dormir","54001","62000"} }'
  default:
    "total": 100
    "actions": [ 'dormir', 'travailler', 'jouer', 'danser']


characters:
  total : 10000

fiction:
  start: 0
  end: 3